-- Options are automatically loaded before the first rendered frame
-- (lazier applies them from the compiled bundle).
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
